apiVersion: v1
kind: Service
metadata:
  name: my-srv-lb
  labels:
    app: my-srv-lb
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: green
  type: LoadBalancer
