apiVersion: v1
kind: Service
metadata:
  name: my-srv
  labels:
    app: my-srv
spec:
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: blue
  type: NodePort
